Repository Hunroll/-projetc-team-05, pull requests merged in 2024-08, with the labels that each got.

#22 11-validate-phone
  .gitignore
  src/models.py
  src/normalize_phone.py
Labels: enhancement, good first issue

#24 14-search-for-user
  src/Bot.py
Labels: enhancement

#25 10-extend-user-model
  src/Bot.py
  src/models.py
Labels: enhancement, good first issue

#29 14-search-for-user
  src/AddressBook.py
  src/Bot.py
Labels: documentation, enhancement, refactoring

#35 32-edit-what-user-old-new
  main.py
  src/AddressBook.py
  src/Bot.py
  src/models.py
Labels: documentation, enhancement, refactoring

#38 32-edit-what-user-old-new
  main.py
  src/AddressBook.py
  src/Bot.py
  src/models.py
Labels: bug, documentation, enhancement, refactoring

#52 [FIX] change filepath
  src/data_base.py
Labels: bug, enhancement, refactoring

#50 documentation
  README.md
  src/AddressBook.py
  src/Bot.py
  src/NoteBook.py
  src/Validator.py
  src/data_base.py
  src/models.py
  task.requirements.txt
Labels: documentation

#54 Packaging
  ccnb/__init__.py
  ccnb/__main__.py
  ccnb/src/AddressBook.py
  ccnb/src/Bot.py
  ccnb/src/NoteBook.py
  ccnb/src/Validator.py
  ccnb/src/data_base.py
  ccnb/src/models.py
  ccnb/src/tests.py
  pyproject.toml
Labels: enhancement, Good to have, refactoring

#53 documentation
  README.md
  ccnb/src/Bot.py
  ccnb/src/data_base.py
  pyproject.toml
Labels: documentation, refactoring
